name: deploy-gh-pages-actions
run-name: ${{ github.actor }} is deploying gh-pages
on:
  push:
    branches: 
      - master
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}"
      - run: mkdir -p ./build/gh-pages
      - run: git init -b gh-pages ./build/gh-pages 
      - run: |
          cd ./build/gh-pages
          git remote add -t gh-pages origin https://github.com/camt-mmit/2022_01-ci-cd-my-react-TopThammanun
      - run: git pull origin
      - run: cp ./build/index.html ./build/404.html
      - run: |
          rm -rf ./build/gh-pages/*
          cp -rf ./build/* ./build/gh-pages/
      - run : |
          cd ./build/gh-pages
          git add .
          git commit -m "Manually commit"
          git push origin gh-pages
